name: GitHub Classroom Workflow
on: [push]
jobs:
  list:
    name: ExamplesTest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '10'
      - run: mvn compile
      - run: mvn -Dtest=currying.ExamplesTest test
