name: manyjobs
on:
  workflow_dispatch:

jobs:

  demorgan:
    name: DeMorganTest
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '10'
      - name: compile
        run: mvn compile
      - name: DeMorganTest
        run: mvn -Dtest=currying.DeMorganTest test
      - name: FactTest
        run: mvn -Dtest=currying.FactTest test


  fact:
    name: FactTest
    needs: demorgan
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '10'
      - run: mvn compile
      - run: mvn -Dtest=currying.FactTest test

  binom:
    name: BinomTest
    needs: fact
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '10'
      - run: mvn compile
      - run: mvn -Dtest=currying.BinomTest test

  ggt:
    name: GgtTest
    needs: binom
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '10'
      - run: mvn compile
      - run: mvn -Dtest=currying.GgtTest test

  fib:
    name: FibTest
    needs: ggt
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '10'
      - run: mvn compile
      - run: mvn -Dtest=currying.FibTest test

